### ISSUE TITLE
[BUG]  botKit conditional branch is not working 

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/botkit-starter-rocketchat#7]
With the default `create_a_reply`  script,   answering `yes` conditionally does not cause the conditional execution of the script `create_script`.

Instead, it goes to the `fallback`.

**Comment by Sing-Li** [comment]
@arthurTemporim   Take a look at how it is implemented in the Slack adapter ...
https://github.com/howdyai/botkit/blob/8fe85d4e318d51f481094b3f4e55303b7572d29d/lib/Slackbot_worker.js#L889

**Comment by diegodorgam** [comment]
this fallback behaviour is actually not done in the starter code, but in botkit studio settings, https://github.com/howdyai/botkit-starter-web/blob/master/docs/botkit_chat_server.md#learning-mode, you must set a `create_a_reply` script in botkit studio and then define it as it's default fallback.
Although, because learning mode sends back buttons, it wouldn't be easy to translate that to rocket.chat.

**Comment by Sing-Li** [comment]
@diegodorgam that's not the problem.  The problem is the inability of the bot to carry a conversation that requires more than one response step.  @arthurTemporim  is enroute on fixing that by implementing a missing method in the adapter -> linked to in my post above.   This has already been verified by the botKit community.

Any of the botKit button -> just sends the configured text response.  So the bot just receives the text response.  The buttons are not relevant to this problem.

**Comment by Sing-Li** [comment]
This is resolved on the connector level https://github.com/RocketChat/botkit-rocketchat-connector

Version 0.0.12 of the npm module fixed this:
https://www.npmjs.com/package/botkit-rocketchat-connector
