### ISSUE TITLE
[BUG] It is not possible to configure a list of rooms for the bot to join at startup

### ISSUE THREAD

**Issue by ear-dev** [RocketChat/botkit-starter-rocketchat#9]
I believe that the ROOM env should handle a comma separated list of rooms to join?

**Comment by timkinnane** [comment]
`ROCKETCHAT_ROOM` should do it @ear-dev. That's a default feature of the SDK's connection handler, so it shouldn't need anything done in the adapter.

https://github.com/RocketChat/Rocket.Chat.js.SDK#settings

**Comment by timkinnane** [comment]
@ear-dev I had another look, it seems the problem is that this package is doing it's own handling of the config, bypassing the settings used in the SDK. The SDK will connect to the rooms as per ENV config when it first sets up the subscription, **unless** it finds rooms already joined, by design to allow SDK developers to take subscriptions off auto for specific use-cases.

All this needs for a fix is to remove the manual call to `joinRooms` here:
https://github.com/RocketChat/botkit-rocketchat-connector/blob/develop/RocketChatBot.js#L18

I don't know where that config is coming from though, it might be intentional for some reason I'm not aware of. I also noticed some options declared that don't seem to be read at all. Here:

https://github.com/RocketChat/botkit-rocketchat-connector/blob/6312392c12d39a5ab5b801c7dd01d27f5d6f0bf7/RocketChatBot.js#L28-L32

I would recommend @arthurTemporim to review the Hubot adapter as a guide for the connection process and simply allow the SDK to handle all the env configs for login and room subscriptions, without passing overriding options. e.g.

https://github.com/RocketChat/hubot-rocketchat/blob/930d085472bb9afa122721fa1b0bec59a783b86b/index.js#L59-L82

**Comment by ear-dev** [comment]
@timkinnane Thanks for taking a look.  I'll test a fix and talk with @arthurTemporim about adjusting the logic as needed.

**Comment by arthurTemporim** [comment]
I removed `joinRooms` in this commit:
[commit](https://github.com/RocketChat/botkit-rocketchat-connector/commit/70b4c5b737c34c19b3b61d1e2aa83c47f4db858e)

About the `options` they are used to configure the behavior of the bot just editing the `.env` file, that allows the bot to answer or not livechat, direct messages or edited messages.
